# baseURL = 'https://til.dchan.cc'
languageCode = 'en-us'
title = 'David Chan - Today I Learned (TIL)'
theme = "papermod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

minify = { disableXML = true, minifyOutput = true }
outputs = { home = ['HTML', 'RSS', 'JSON'] }
env = "production"
ignoreLogs = ['warning-goldmark-raw-html']


[params]
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
UseHugoToc = true
comments = false
showtoc = false
tocopen = false
description = "Examples of things I've learned today"
socialIcons = [{ name = "rss", url = "https://til.dchan.cc/posts/index.xml" }]

[params.assets]
disableFingerprinting = true

[params.homeInfoParams]
content = "Hi! I'm David. Here are some things I've learned..."

[menu]
main = [
    { identifier = "search", name = "Search", url = "/search", weight = 1 },
    { identifier = "archives", name = "Archives", url = "/posts", weight = 2 },
    { identifier = "About", name = "Me", url = "https://dchan.cc", weight = 3 },
]
